### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by klein0r** [herrJones/node-comfoairq#3]
When using the sens command in comfoTest:

```
zehnder command to test (? for help): sens
register to updates on sensors

comfo : TX error -> {} -> 7/14/2020, 11:25:59 PM
(node:64668) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'kind' of undefined
    at Object.cmd_RegisterSensor (/Users/matthiaskleine/Dev/node-comfoairq/lib/preparation.js:160:22)
    at /Users/matthiaskleine/Dev/node-comfoairq/lib/comfoconnect.js:479:27
    at new Promise (<anonymous>)
    at ComfoAirQ.RegisterSensor (/Users/matthiaskleine/Dev/node-comfoairq/lib/comfoconnect.js:476:10)
    at /Users/matthiaskleine/Dev/node-comfoairq/test/comfoTest.js:152:40
    at Interface._onLine (readline.js:327:5)
    at Interface._line (readline.js:658:8)
    at Interface._ttyWrite (readline.js:999:14)
    at ReadStream.onkeypress (readline.js:205:10)
    at ReadStream.emit (events.js:315:20)
(node:64668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:64668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by herrJones** [comment]
valid codes are defined in https://github.com/herrJones/node-comfoairq/blob/master/lib/const.js
